{
	"stock and mf api": [{
			"company_name": "COAL INDIA LIMITED",
			"company_symbol": "COALINDIA",
			"company_image": "https://static.india.com/wp-content/uploads/2015/03/coal-india.jpg?impolicy=Medium_Resize&w=1200&h=800",
			"company_current_price": "185.6",
			"percent_gain": "+1.80%",
			"percent_loss": "-.08%",
			"price_gain": "+3.21",
			"price_loss": "-0.15",
			"mf_name": "Axis Bluechip Fund",
			"mf_sector": "Equity Sectoral/ Thermal . 5 *",
			"mf_percentage": "39.88",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://yt3.ggpht.com/ytc/AKedOLQE8hgs4c07sR6zoRQPG2wpX6G598z0VCKyr5Di0g=s900-c-k-c0x00ffffff-no-rj",
			"qa_heading": "NFO Live",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "HCL TECHNOLOGIES LIMITED",
			"company_symbol": "HCLTECH",
			"company_image": "https://pbs.twimg.com/profile_images/1410304847656611841/l2tjvIDP_400x400.jpg",
			"company_current_price": "1281",
			"percent_gain": "+0.80%",
			"percent_loss": "-.2%",
			"price_gain": "+8.21",
			"price_loss": "-2.15",
			"mf_name": "Mirae Asset Large Cap Fund",
			"mf_sector": "Equity Sectoral/ Thermal . 4.4 *",
			"mf_percentage": "17.88",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://www.wealthzi.com/wp-content/uploads/2021/04/MIRAS.png",
			"qa_heading": "Import Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "WIPRO",
			"company_symbol": "WIPRO",
			"company_image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Wipro_Primary_Logo_Color_RGB.svg/1200px-Wipro_Primary_Logo_Color_RGB.svg.png",
			"company_current_price": "643",
			"percent_gain": "+1.0%",
			"percent_loss": "0.0",
			"price_gain": "+6.2",
			"price_loss": "-0.0",
			"mf_name": "Parag Parikh Long",
			"mf_sector": "Equity Sectoral . 4.2 *",
			"mf_percentage": "17.68",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://static.paytmmoney.com/amc-logo/PPFAS.png",
			"qa_heading": "Export Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "TATA MOTORS LIMITED",
			"company_symbol": "TATAMOTORS",
			"company_image": "https://pbs.twimg.com/profile_images/899609798299205633/DZLt0_e2_400x400.jpg",
			"company_current_price": "331.25",
			"percent_gain": "+3.25%",
			"percent_loss": "-1.25",
			"price_gain": "+9.55",
			"price_loss": "-3.05",
			"mf_name": "Kotak Standard Multicap Fund",
			"mf_sector": "Equity Sectoral . 4.2 *",
			"mf_percentage": "17.05",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://bsmedia.business-standard.com/media-handler.php?mediaPath=https://bsmedia.business-standard.com/_media/bs/img/article/2019-04/13/full/1555102799-1041.jpg&width=1200",
			"qa_heading": "Government Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "NTPC LIMITED",
			"company_symbol": "NTPC",
			"company_image": "https://pbs.twimg.com/profile_images/899609798299205633/DZLt0_e2_400x400.jpg",
			"company_current_price": "140.25",
			"percent_gain": "+0.36%",
			"percent_loss": "0.0",
			"price_gain": "+0.50",
			"price_loss": "0.0",
			"mf_name": "Axis Small Cap Fund",
			"mf_sector": "Equity Sectoral . 4.0 *",
			"mf_percentage": "16.95",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://is4-ssl.mzstatic.com/image/thumb/Purple115/v4/10/30/84/103084d1-ede0-2563-7bce-3cddfce9cc4b/AppIcon-0-0-1x_U007emarketing-0-0-0-10-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/600x600wa.png",
			"qa_heading": "Private Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "JSW STEEL LIMITED",
			"company_symbol": "JSW",
			"company_image": "https://csrbox.org/company/cmp_logo/1573907302jsw-steel.jpg",
			"company_current_price": "675.90",
			"percent_gain": "0.00",
			"percent_loss": "-.057",
			"price_gain": "+0.00",
			"price_loss": "-3.90",
			"mf_name": "DSP Midcap Fund",
			"mf_sector": "Equity Sectoral . 3.9 *",
			"mf_percentage": "16.70",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://static.paytmmoney.com/amc-logo/DSPBR.png",
			"qa_heading": "SmallCap Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "ULTRATECH CEMENT LIMITED",
			"company_symbol": "ULTRACEMCO",
			"company_image": "https://companiesmarketcap.com/img/company-logos/256/ULTRACEMCO.NS.png",
			"company_current_price": "7416.30",
			"percent_gain": "+0.00",
			"percent_loss": "-0.65",
			"price_gain": "+0.00",
			"price_loss": "-48.25",
			"mf_name": "SBI Smallcap Fund",
			"mf_sector": "Equity Sectoral . 3.7 *",
			"mf_percentage": "16.60",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://admin.mysiponline.com/app/webroot/blog_uploadimages/1530090062cover-min_(15).jpg",
			"qa_heading": "MidCap Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "MARUTI SUZUKI INDIA LIMITED",
			"company_symbol": "MARUTI",
			"company_image": "https://qph.fs.quoracdn.net/main-qimg-b1e116ff5948fbcb85729949237943de.webp",
			"company_current_price": "7375.30",
			"percent_gain": "+0.020",
			"percent_loss": "-0.12",
			"price_gain": "+11.25",
			"price_loss": "-9.05",
			"mf_name": "SBI Equity Hybrid Fund",
			"mf_sector": "Equity Sectoral . 3.5 *",
			"mf_percentage": "16.30",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://i.ytimg.com/vi/QDvJ-CCknwQ/maxresdefault.jpg",
			"qa_heading": "Fortune500 Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "CIPLA LIMITED",
			"company_symbol": "CIPLA",
			"company_image": "https://1.bp.blogspot.com/-a2VJSu7Va6M/XcLFbrfVoTI/AAAAAAAAgZA/i1Cdc-XpZE4nDyIEU3EDULQ0ke80yeLjgCLcBGAsYHQ/s1600/Cipla.jpg",
			"company_current_price": "991.00",
			"percent_gain": "0.34",
			"percent_loss": "-0.00",
			"price_gain": "+3.40",
			"price_loss": "-0.0",
			"mf_name": "Mirae Asset Hybrid Equity Fund",
			"mf_sector": "Equity Sectoral . 3.3 *",
			"mf_percentage": "16.30",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://static.paytmmoney.com/amc-logo/MIRAS.png",
			"qa_heading": "Fortune100 Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "DIVI'S LABORATORIES LIMITED",
			"company_symbol": "DIVISLAB",
			"company_image": "https://upload.wikimedia.org/wikipedia/en/thumb/3/30/Divi%27s_Laboratories_Logo.svg/1200px-Divi%27s_Laboratories_Logo.svg.png",
			"company_current_price": "4830.95",
			"percent_gain": "+0.51",
			"percent_loss": "-0.00",
			"price_gain": "+24.50",
			"price_loss": "-0.0",
			"mf_name": "Sundaram Large and Midcap Fund",
			"mf_sector": "Equity Sectoral . 3.2 *",
			"mf_percentage": "16.20",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://static.paytmmoney.com/amc-logo/SNDRM.png",
			"qa_heading": "Fortune50 Fund",
			"qa_desc": "Invest in New Fund Offering"
		},
		{
			"company_name": "COAL INDIA LIMITED",
			"company_symbol": "COALINDIA",
			"company_image": "https://static.india.com/wp-content/uploads/2015/03/coal-india.jpg?impolicy=Medium_Resize&w=1200&h=800",
			"company_current_price": "185.6",
			"percent_gain": "+1.80%",
			"percent_loss": "-.08%",
			"price_gain": "+3.21",
			"price_loss": "-0.15",
			"mf_name": "Axis Bluechip Fund",
			"mf_sector": "Equity Sectoral/ Thermal . 5 *",
			"mf_percentage": "39.88",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://yt3.ggpht.com/ytc/AKedOLQE8hgs4c07sR6zoRQPG2wpX6G598z0VCKyr5Di0g=s900-c-k-c0x00ffffff-no-rj",
			"qa_heading": "NFO Live",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "HCL TECHNOLOGIES LIMITED",
			"company_symbol": "HCLTECH",
			"company_image": "https://pbs.twimg.com/profile_images/1410304847656611841/l2tjvIDP_400x400.jpg",
			"company_current_price": "1281",
			"percent_gain": "+0.80%",
			"percent_loss": "-.2%",
			"price_gain": "+8.21",
			"price_loss": "-2.15",
			"mf_name": "Mirae Asset Large Cap Fund",
			"mf_sector": "Equity Sectoral/ Thermal . 4.4 *",
			"mf_percentage": "17.88",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://www.wealthzi.com/wp-content/uploads/2021/04/MIRAS.png",
			"qa_heading": "Import Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "WIPRO",
			"company_symbol": "WIPRO",
			"company_image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Wipro_Primary_Logo_Color_RGB.svg/1200px-Wipro_Primary_Logo_Color_RGB.svg.png",
			"company_current_price": "643",
			"percent_gain": "+1.0%",
			"percent_loss": "0.0",
			"price_gain": "+6.2",
			"price_loss": "-0.0",
			"mf_name": "Parag Parikh Long",
			"mf_sector": "Equity Sectoral . 4.2 *",
			"mf_percentage": "17.68",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://static.paytmmoney.com/amc-logo/PPFAS.png",
			"qa_heading": "Export Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "TATA MOTORS LIMITED",
			"company_symbol": "TATAMOTORS",
			"company_image": "https://pbs.twimg.com/profile_images/899609798299205633/DZLt0_e2_400x400.jpg",
			"company_current_price": "331.25",
			"percent_gain": "+3.25%",
			"percent_loss": "-1.25",
			"price_gain": "+9.55",
			"price_loss": "-3.05",
			"mf_name": "Kotak Standard Multicap Fund",
			"mf_sector": "Equity Sectoral . 4.2 *",
			"mf_percentage": "17.05",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://bsmedia.business-standard.com/media-handler.php?mediaPath=https://bsmedia.business-standard.com/_media/bs/img/article/2019-04/13/full/1555102799-1041.jpg&width=1200",
			"qa_heading": "Government Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "NTPC LIMITED",
			"company_symbol": "NTPC",
			"company_image": "https://pbs.twimg.com/profile_images/899609798299205633/DZLt0_e2_400x400.jpg",
			"company_current_price": "140.25",
			"percent_gain": "+0.36%",
			"percent_loss": "0.0",
			"price_gain": "+0.50",
			"price_loss": "0.0",
			"mf_name": "Axis Small Cap Fund",
			"mf_sector": "Equity Sectoral . 4.0 *",
			"mf_percentage": "16.95",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://is4-ssl.mzstatic.com/image/thumb/Purple115/v4/10/30/84/103084d1-ede0-2563-7bce-3cddfce9cc4b/AppIcon-0-0-1x_U007emarketing-0-0-0-10-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/600x600wa.png",
			"qa_heading": "Private Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "JSW STEEL LIMITED",
			"company_symbol": "JSW",
			"company_image": "https://csrbox.org/company/cmp_logo/1573907302jsw-steel.jpg",
			"company_current_price": "675.90",
			"percent_gain": "0.00",
			"percent_loss": "-.057",
			"price_gain": "+0.00",
			"price_loss": "-3.90",
			"mf_name": "DSP Midcap Fund",
			"mf_sector": "Equity Sectoral . 3.9 *",
			"mf_percentage": "16.70",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://static.paytmmoney.com/amc-logo/DSPBR.png",
			"qa_heading": "SmallCap Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "ULTRATECH CEMENT LIMITED",
			"company_symbol": "ULTRACEMCO",
			"company_image": "https://companiesmarketcap.com/img/company-logos/256/ULTRACEMCO.NS.png",
			"company_current_price": "7416.30",
			"percent_gain": "+0.00",
			"percent_loss": "-0.65",
			"price_gain": "+0.00",
			"price_loss": "-48.25",
			"mf_name": "SBI Smallcap Fund",
			"mf_sector": "Equity Sectoral . 3.7 *",
			"mf_percentage": "16.60",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://admin.mysiponline.com/app/webroot/blog_uploadimages/1530090062cover-min_(15).jpg",
			"qa_heading": "MidCap Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "MARUTI SUZUKI INDIA LIMITED",
			"company_symbol": "MARUTI",
			"company_image": "https://qph.fs.quoracdn.net/main-qimg-b1e116ff5948fbcb85729949237943de.webp",
			"company_current_price": "7375.30",
			"percent_gain": "+0.020",
			"percent_loss": "-0.12",
			"price_gain": "+11.25",
			"price_loss": "-9.05",
			"mf_name": "SBI Equity Hybrid Fund",
			"mf_sector": "Equity Sectoral . 3.5 *",
			"mf_percentage": "16.30",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://i.ytimg.com/vi/QDvJ-CCknwQ/maxresdefault.jpg",
			"qa_heading": "Fortune500 Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "CIPLA LIMITED",
			"company_symbol": "CIPLA",
			"company_image": "https://1.bp.blogspot.com/-a2VJSu7Va6M/XcLFbrfVoTI/AAAAAAAAgZA/i1Cdc-XpZE4nDyIEU3EDULQ0ke80yeLjgCLcBGAsYHQ/s1600/Cipla.jpg",
			"company_current_price": "991.00",
			"percent_gain": "0.34",
			"percent_loss": "-0.00",
			"price_gain": "+3.40",
			"price_loss": "-0.0",
			"mf_name": "Mirae Asset Hybrid Equity Fund",
			"mf_sector": "Equity Sectoral . 3.3 *",
			"mf_percentage": "16.30",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://static.paytmmoney.com/amc-logo/MIRAS.png",
			"qa_heading": "Fortune100 Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "DIVI'S LABORATORIES LIMITED",
			"company_symbol": "DIVISLAB",
			"company_image": "https://upload.wikimedia.org/wikipedia/en/thumb/3/30/Divi%27s_Laboratories_Logo.svg/1200px-Divi%27s_Laboratories_Logo.svg.png",
			"company_current_price": "4830.95",
			"percent_gain": "+0.51",
			"percent_loss": "-0.00",
			"price_gain": "+24.50",
			"price_loss": "-0.0",
			"mf_name": "Sundaram Large and Midcap Fund",
			"mf_sector": "Equity Sectoral . 3.2 *",
			"mf_percentage": "16.20",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://static.paytmmoney.com/amc-logo/SNDRM.png",
			"qa_heading": "Fortune50 Fund",
			"qa_desc": "Invest in New Fund Offering"
		},
		{
			"company_name": "COAL INDIA LIMITED",
			"company_symbol": "COALINDIA",
			"company_image": "https://static.india.com/wp-content/uploads/2015/03/coal-india.jpg?impolicy=Medium_Resize&w=1200&h=800",
			"company_current_price": "185.6",
			"percent_gain": "+1.80%",
			"percent_loss": "-.08%",
			"price_gain": "+3.21",
			"price_loss": "-0.15",
			"mf_name": "Axis Bluechip Fund",
			"mf_sector": "Equity Sectoral/ Thermal . 5 *",
			"mf_percentage": "39.88",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://yt3.ggpht.com/ytc/AKedOLQE8hgs4c07sR6zoRQPG2wpX6G598z0VCKyr5Di0g=s900-c-k-c0x00ffffff-no-rj",
			"qa_heading": "NFO Live",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "HCL TECHNOLOGIES LIMITED",
			"company_symbol": "HCLTECH",
			"company_image": "https://pbs.twimg.com/profile_images/1410304847656611841/l2tjvIDP_400x400.jpg",
			"company_current_price": "1281",
			"percent_gain": "+0.80%",
			"percent_loss": "-.2%",
			"price_gain": "+8.21",
			"price_loss": "-2.15",
			"mf_name": "Mirae Asset Large Cap Fund",
			"mf_sector": "Equity Sectoral/ Thermal . 4.4 *",
			"mf_percentage": "17.88",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://www.wealthzi.com/wp-content/uploads/2021/04/MIRAS.png",
			"qa_heading": "Import Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "WIPRO",
			"company_symbol": "WIPRO",
			"company_image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Wipro_Primary_Logo_Color_RGB.svg/1200px-Wipro_Primary_Logo_Color_RGB.svg.png",
			"company_current_price": "643",
			"percent_gain": "+1.0%",
			"percent_loss": "0.0",
			"price_gain": "+6.2",
			"price_loss": "-0.0",
			"mf_name": "Parag Parikh Long",
			"mf_sector": "Equity Sectoral . 4.2 *",
			"mf_percentage": "17.68",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://static.paytmmoney.com/amc-logo/PPFAS.png",
			"qa_heading": "Export Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "TATA MOTORS LIMITED",
			"company_symbol": "TATAMOTORS",
			"company_image": "https://pbs.twimg.com/profile_images/899609798299205633/DZLt0_e2_400x400.jpg",
			"company_current_price": "331.25",
			"percent_gain": "+3.25%",
			"percent_loss": "-1.25",
			"price_gain": "+9.55",
			"price_loss": "-3.05",
			"mf_name": "Kotak Standard Multicap Fund",
			"mf_sector": "Equity Sectoral . 4.2 *",
			"mf_percentage": "17.05",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://bsmedia.business-standard.com/media-handler.php?mediaPath=https://bsmedia.business-standard.com/_media/bs/img/article/2019-04/13/full/1555102799-1041.jpg&width=1200",
			"qa_heading": "Government Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "NTPC LIMITED",
			"company_symbol": "NTPC",
			"company_image": "https://pbs.twimg.com/profile_images/899609798299205633/DZLt0_e2_400x400.jpg",
			"company_current_price": "140.25",
			"percent_gain": "+0.36%",
			"percent_loss": "0.0",
			"price_gain": "+0.50",
			"price_loss": "0.0",
			"mf_name": "Axis Small Cap Fund",
			"mf_sector": "Equity Sectoral . 4.0 *",
			"mf_percentage": "16.95",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://is4-ssl.mzstatic.com/image/thumb/Purple115/v4/10/30/84/103084d1-ede0-2563-7bce-3cddfce9cc4b/AppIcon-0-0-1x_U007emarketing-0-0-0-10-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/600x600wa.png",
			"qa_heading": "Private Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "JSW STEEL LIMITED",
			"company_symbol": "JSW",
			"company_image": "https://csrbox.org/company/cmp_logo/1573907302jsw-steel.jpg",
			"company_current_price": "675.90",
			"percent_gain": "0.00",
			"percent_loss": "-.057",
			"price_gain": "+0.00",
			"price_loss": "-3.90",
			"mf_name": "DSP Midcap Fund",
			"mf_sector": "Equity Sectoral . 3.9 *",
			"mf_percentage": "16.70",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://static.paytmmoney.com/amc-logo/DSPBR.png",
			"qa_heading": "SmallCap Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "ULTRATECH CEMENT LIMITED",
			"company_symbol": "ULTRACEMCO",
			"company_image": "https://companiesmarketcap.com/img/company-logos/256/ULTRACEMCO.NS.png",
			"company_current_price": "7416.30",
			"percent_gain": "+0.00",
			"percent_loss": "-0.65",
			"price_gain": "+0.00",
			"price_loss": "-48.25",
			"mf_name": "SBI Smallcap Fund",
			"mf_sector": "Equity Sectoral . 3.7 *",
			"mf_percentage": "16.60",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://admin.mysiponline.com/app/webroot/blog_uploadimages/1530090062cover-min_(15).jpg",
			"qa_heading": "MidCap Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "MARUTI SUZUKI INDIA LIMITED",
			"company_symbol": "MARUTI",
			"company_image": "https://qph.fs.quoracdn.net/main-qimg-b1e116ff5948fbcb85729949237943de.webp",
			"company_current_price": "7375.30",
			"percent_gain": "+0.020",
			"percent_loss": "-0.12",
			"price_gain": "+11.25",
			"price_loss": "-9.05",
			"mf_name": "SBI Equity Hybrid Fund",
			"mf_sector": "Equity Sectoral . 3.5 *",
			"mf_percentage": "16.30",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://i.ytimg.com/vi/QDvJ-CCknwQ/maxresdefault.jpg",
			"qa_heading": "Fortune500 Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "CIPLA LIMITED",
			"company_symbol": "CIPLA",
			"company_image": "https://1.bp.blogspot.com/-a2VJSu7Va6M/XcLFbrfVoTI/AAAAAAAAgZA/i1Cdc-XpZE4nDyIEU3EDULQ0ke80yeLjgCLcBGAsYHQ/s1600/Cipla.jpg",
			"company_current_price": "991.00",
			"percent_gain": "0.34",
			"percent_loss": "-0.00",
			"price_gain": "+3.40",
			"price_loss": "-0.0",
			"mf_name": "Mirae Asset Hybrid Equity Fund",
			"mf_sector": "Equity Sectoral . 3.3 *",
			"mf_percentage": "16.30",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://static.paytmmoney.com/amc-logo/MIRAS.png",
			"qa_heading": "Fortune100 Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "DIVI'S LABORATORIES LIMITED",
			"company_symbol": "DIVISLAB",
			"company_image": "https://upload.wikimedia.org/wikipedia/en/thumb/3/30/Divi%27s_Laboratories_Logo.svg/1200px-Divi%27s_Laboratories_Logo.svg.png",
			"company_current_price": "4830.95",
			"percent_gain": "+0.51",
			"percent_loss": "-0.00",
			"price_gain": "+24.50",
			"price_loss": "-0.0",
			"mf_name": "Sundaram Large and Midcap Fund",
			"mf_sector": "Equity Sectoral . 3.2 *",
			"mf_percentage": "16.20",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://static.paytmmoney.com/amc-logo/SNDRM.png",
			"qa_heading": "Fortune50 Fund",
			"qa_desc": "Invest in New Fund Offering"
		},
		{
			"company_name": "COAL INDIA LIMITED",
			"company_symbol": "COALINDIA",
			"company_image": "https://static.india.com/wp-content/uploads/2015/03/coal-india.jpg?impolicy=Medium_Resize&w=1200&h=800",
			"company_current_price": "185.6",
			"percent_gain": "+1.80%",
			"percent_loss": "-.08%",
			"price_gain": "+3.21",
			"price_loss": "-0.15",
			"mf_name": "Axis Bluechip Fund",
			"mf_sector": "Equity Sectoral/ Thermal . 5 *",
			"mf_percentage": "39.88",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://yt3.ggpht.com/ytc/AKedOLQE8hgs4c07sR6zoRQPG2wpX6G598z0VCKyr5Di0g=s900-c-k-c0x00ffffff-no-rj",
			"qa_heading": "NFO Live",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "HCL TECHNOLOGIES LIMITED",
			"company_symbol": "HCLTECH",
			"company_image": "https://pbs.twimg.com/profile_images/1410304847656611841/l2tjvIDP_400x400.jpg",
			"company_current_price": "1281",
			"percent_gain": "+0.80%",
			"percent_loss": "-.2%",
			"price_gain": "+8.21",
			"price_loss": "-2.15",
			"mf_name": "Mirae Asset Large Cap Fund",
			"mf_sector": "Equity Sectoral/ Thermal . 4.4 *",
			"mf_percentage": "17.88",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://www.wealthzi.com/wp-content/uploads/2021/04/MIRAS.png",
			"qa_heading": "Import Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "WIPRO",
			"company_symbol": "WIPRO",
			"company_image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Wipro_Primary_Logo_Color_RGB.svg/1200px-Wipro_Primary_Logo_Color_RGB.svg.png",
			"company_current_price": "643",
			"percent_gain": "+1.0%",
			"percent_loss": "0.0",
			"price_gain": "+6.2",
			"price_loss": "-0.0",
			"mf_name": "Parag Parikh Long",
			"mf_sector": "Equity Sectoral . 4.2 *",
			"mf_percentage": "17.68",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://static.paytmmoney.com/amc-logo/PPFAS.png",
			"qa_heading": "Export Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "TATA MOTORS LIMITED",
			"company_symbol": "TATAMOTORS",
			"company_image": "https://pbs.twimg.com/profile_images/899609798299205633/DZLt0_e2_400x400.jpg",
			"company_current_price": "331.25",
			"percent_gain": "+3.25%",
			"percent_loss": "-1.25",
			"price_gain": "+9.55",
			"price_loss": "-3.05",
			"mf_name": "Kotak Standard Multicap Fund",
			"mf_sector": "Equity Sectoral . 4.2 *",
			"mf_percentage": "17.05",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://bsmedia.business-standard.com/media-handler.php?mediaPath=https://bsmedia.business-standard.com/_media/bs/img/article/2019-04/13/full/1555102799-1041.jpg&width=1200",
			"qa_heading": "Government Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "NTPC LIMITED",
			"company_symbol": "NTPC",
			"company_image": "https://pbs.twimg.com/profile_images/899609798299205633/DZLt0_e2_400x400.jpg",
			"company_current_price": "140.25",
			"percent_gain": "+0.36%",
			"percent_loss": "0.0",
			"price_gain": "+0.50",
			"price_loss": "0.0",
			"mf_name": "Axis Small Cap Fund",
			"mf_sector": "Equity Sectoral . 4.0 *",
			"mf_percentage": "16.95",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://is4-ssl.mzstatic.com/image/thumb/Purple115/v4/10/30/84/103084d1-ede0-2563-7bce-3cddfce9cc4b/AppIcon-0-0-1x_U007emarketing-0-0-0-10-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/600x600wa.png",
			"qa_heading": "Private Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "JSW STEEL LIMITED",
			"company_symbol": "JSW",
			"company_image": "https://csrbox.org/company/cmp_logo/1573907302jsw-steel.jpg",
			"company_current_price": "675.90",
			"percent_gain": "0.00",
			"percent_loss": "-.057",
			"price_gain": "+0.00",
			"price_loss": "-3.90",
			"mf_name": "DSP Midcap Fund",
			"mf_sector": "Equity Sectoral . 3.9 *",
			"mf_percentage": "16.70",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://static.paytmmoney.com/amc-logo/DSPBR.png",
			"qa_heading": "SmallCap Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "ULTRATECH CEMENT LIMITED",
			"company_symbol": "ULTRACEMCO",
			"company_image": "https://companiesmarketcap.com/img/company-logos/256/ULTRACEMCO.NS.png",
			"company_current_price": "7416.30",
			"percent_gain": "+0.00",
			"percent_loss": "-0.65",
			"price_gain": "+0.00",
			"price_loss": "-48.25",
			"mf_name": "SBI Smallcap Fund",
			"mf_sector": "Equity Sectoral . 3.7 *",
			"mf_percentage": "16.60",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://admin.mysiponline.com/app/webroot/blog_uploadimages/1530090062cover-min_(15).jpg",
			"qa_heading": "MidCap Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "MARUTI SUZUKI INDIA LIMITED",
			"company_symbol": "MARUTI",
			"company_image": "https://qph.fs.quoracdn.net/main-qimg-b1e116ff5948fbcb85729949237943de.webp",
			"company_current_price": "7375.30",
			"percent_gain": "+0.020",
			"percent_loss": "-0.12",
			"price_gain": "+11.25",
			"price_loss": "-9.05",
			"mf_name": "SBI Equity Hybrid Fund",
			"mf_sector": "Equity Sectoral . 3.5 *",
			"mf_percentage": "16.30",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://i.ytimg.com/vi/QDvJ-CCknwQ/maxresdefault.jpg",
			"qa_heading": "Fortune500 Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "CIPLA LIMITED",
			"company_symbol": "CIPLA",
			"company_image": "https://1.bp.blogspot.com/-a2VJSu7Va6M/XcLFbrfVoTI/AAAAAAAAgZA/i1Cdc-XpZE4nDyIEU3EDULQ0ke80yeLjgCLcBGAsYHQ/s1600/Cipla.jpg",
			"company_current_price": "991.00",
			"percent_gain": "0.34",
			"percent_loss": "-0.00",
			"price_gain": "+3.40",
			"price_loss": "-0.0",
			"mf_name": "Mirae Asset Hybrid Equity Fund",
			"mf_sector": "Equity Sectoral . 3.3 *",
			"mf_percentage": "16.30",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://static.paytmmoney.com/amc-logo/MIRAS.png",
			"qa_heading": "Fortune100 Fund",
			"qa_desc": "Invest in New Fund Offering"
		}, {
			"company_name": "DIVI'S LABORATORIES LIMITED",
			"company_symbol": "DIVISLAB",
			"company_image": "https://upload.wikimedia.org/wikipedia/en/thumb/3/30/Divi%27s_Laboratories_Logo.svg/1200px-Divi%27s_Laboratories_Logo.svg.png",
			"company_current_price": "4830.95",
			"percent_gain": "+0.51",
			"percent_loss": "-0.00",
			"price_gain": "+24.50",
			"price_loss": "-0.0",
			"mf_name": "Sundaram Large and Midcap Fund",
			"mf_sector": "Equity Sectoral . 3.2 *",
			"mf_percentage": "16.20",
			"mf_year_return": "3Y Returns",
			"mf_logo": "https://static.paytmmoney.com/amc-logo/SNDRM.png",
			"qa_heading": "Fortune50 Fund",
			"qa_desc": "Invest in New Fund Offering"
		}
	]
}
